//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsCaller.LemonWayReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LemonWayReference.LemonWayWSSoap")]
    public interface LemonWayWSSoap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément FibonacciResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Fibonacci", ReplyAction="*")]
        WindowsFormsCaller.LemonWayReference.FibonacciResponse Fibonacci(WindowsFormsCaller.LemonWayReference.FibonacciRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Fibonacci", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsCaller.LemonWayReference.FibonacciResponse> FibonacciAsync(WindowsFormsCaller.LemonWayReference.FibonacciRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément xml de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XmlToJson", ReplyAction="*")]
        WindowsFormsCaller.LemonWayReference.XmlToJsonResponse XmlToJson(WindowsFormsCaller.LemonWayReference.XmlToJsonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XmlToJson", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsCaller.LemonWayReference.XmlToJsonResponse> XmlToJsonAsync(WindowsFormsCaller.LemonWayReference.XmlToJsonRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FibonacciRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Fibonacci", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsCaller.LemonWayReference.FibonacciRequestBody Body;
        
        public FibonacciRequest() {
        }
        
        public FibonacciRequest(WindowsFormsCaller.LemonWayReference.FibonacciRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FibonacciRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int n;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool sleep;
        
        public FibonacciRequestBody() {
        }
        
        public FibonacciRequestBody(int n, bool sleep) {
            this.n = n;
            this.sleep = sleep;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FibonacciResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FibonacciResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsCaller.LemonWayReference.FibonacciResponseBody Body;
        
        public FibonacciResponse() {
        }
        
        public FibonacciResponse(WindowsFormsCaller.LemonWayReference.FibonacciResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FibonacciResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FibonacciResult;
        
        public FibonacciResponseBody() {
        }
        
        public FibonacciResponseBody(string FibonacciResult) {
            this.FibonacciResult = FibonacciResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XmlToJsonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XmlToJson", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsCaller.LemonWayReference.XmlToJsonRequestBody Body;
        
        public XmlToJsonRequest() {
        }
        
        public XmlToJsonRequest(WindowsFormsCaller.LemonWayReference.XmlToJsonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class XmlToJsonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        public XmlToJsonRequestBody() {
        }
        
        public XmlToJsonRequestBody(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XmlToJsonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XmlToJsonResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsCaller.LemonWayReference.XmlToJsonResponseBody Body;
        
        public XmlToJsonResponse() {
        }
        
        public XmlToJsonResponse(WindowsFormsCaller.LemonWayReference.XmlToJsonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class XmlToJsonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string XmlToJsonResult;
        
        public XmlToJsonResponseBody() {
        }
        
        public XmlToJsonResponseBody(string XmlToJsonResult) {
            this.XmlToJsonResult = XmlToJsonResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LemonWayWSSoapChannel : WindowsFormsCaller.LemonWayReference.LemonWayWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LemonWayWSSoapClient : System.ServiceModel.ClientBase<WindowsFormsCaller.LemonWayReference.LemonWayWSSoap>, WindowsFormsCaller.LemonWayReference.LemonWayWSSoap {
        
        public LemonWayWSSoapClient() {
        }
        
        public LemonWayWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LemonWayWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LemonWayWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LemonWayWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsCaller.LemonWayReference.FibonacciResponse WindowsFormsCaller.LemonWayReference.LemonWayWSSoap.Fibonacci(WindowsFormsCaller.LemonWayReference.FibonacciRequest request) {
            return base.Channel.Fibonacci(request);
        }
        
        public string Fibonacci(int n, bool sleep) {
            WindowsFormsCaller.LemonWayReference.FibonacciRequest inValue = new WindowsFormsCaller.LemonWayReference.FibonacciRequest();
            inValue.Body = new WindowsFormsCaller.LemonWayReference.FibonacciRequestBody();
            inValue.Body.n = n;
            inValue.Body.sleep = sleep;
            WindowsFormsCaller.LemonWayReference.FibonacciResponse retVal = ((WindowsFormsCaller.LemonWayReference.LemonWayWSSoap)(this)).Fibonacci(inValue);
            return retVal.Body.FibonacciResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsCaller.LemonWayReference.FibonacciResponse> WindowsFormsCaller.LemonWayReference.LemonWayWSSoap.FibonacciAsync(WindowsFormsCaller.LemonWayReference.FibonacciRequest request) {
            return base.Channel.FibonacciAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsCaller.LemonWayReference.FibonacciResponse> FibonacciAsync(int n, bool sleep) {
            WindowsFormsCaller.LemonWayReference.FibonacciRequest inValue = new WindowsFormsCaller.LemonWayReference.FibonacciRequest();
            inValue.Body = new WindowsFormsCaller.LemonWayReference.FibonacciRequestBody();
            inValue.Body.n = n;
            inValue.Body.sleep = sleep;
            return ((WindowsFormsCaller.LemonWayReference.LemonWayWSSoap)(this)).FibonacciAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsCaller.LemonWayReference.XmlToJsonResponse WindowsFormsCaller.LemonWayReference.LemonWayWSSoap.XmlToJson(WindowsFormsCaller.LemonWayReference.XmlToJsonRequest request) {
            return base.Channel.XmlToJson(request);
        }
        
        public string XmlToJson(string xml) {
            WindowsFormsCaller.LemonWayReference.XmlToJsonRequest inValue = new WindowsFormsCaller.LemonWayReference.XmlToJsonRequest();
            inValue.Body = new WindowsFormsCaller.LemonWayReference.XmlToJsonRequestBody();
            inValue.Body.xml = xml;
            WindowsFormsCaller.LemonWayReference.XmlToJsonResponse retVal = ((WindowsFormsCaller.LemonWayReference.LemonWayWSSoap)(this)).XmlToJson(inValue);
            return retVal.Body.XmlToJsonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsCaller.LemonWayReference.XmlToJsonResponse> WindowsFormsCaller.LemonWayReference.LemonWayWSSoap.XmlToJsonAsync(WindowsFormsCaller.LemonWayReference.XmlToJsonRequest request) {
            return base.Channel.XmlToJsonAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsCaller.LemonWayReference.XmlToJsonResponse> XmlToJsonAsync(string xml) {
            WindowsFormsCaller.LemonWayReference.XmlToJsonRequest inValue = new WindowsFormsCaller.LemonWayReference.XmlToJsonRequest();
            inValue.Body = new WindowsFormsCaller.LemonWayReference.XmlToJsonRequestBody();
            inValue.Body.xml = xml;
            return ((WindowsFormsCaller.LemonWayReference.LemonWayWSSoap)(this)).XmlToJsonAsync(inValue);
        }
    }
}
